#!/bin/zsh

# Sheldon
if command -v sheldon &>/dev/null; then
  sheldon_cache_file="${XDG_CACHE_HOME}/sheldon/plugins.zsh"
  sheldon_config_file="${XDG_CONFIG_HOME}/sheldon/plugins.toml"
  if [[ ! -r "$sheldon_cache_file" || "$sheldon_config_file" -nt "$sheldon_cache_file" ]]; then
    mkdir -p "${XDG_CACHE_HOME}/sheldon"
    sheldon source > "$sheldon_cache_file"
  fi
  source "$sheldon_cache_file"
  unset sheldon_cache_file sheldon_config_file
fi

# Editor
export EDITOR="nano"
export VISUAL="$EDITOR"

# Pager
export PAGER="bat --paging=always"
export BAT_PAGER="less"
export LESS="-RFMSWi -#4"
export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"

# History
export HISTFILE="${XDG_STATE_HOME}/zsh/history"
export HISTFILESIZE=100000
export HISTSIZE=100000
export SAVEHIST=100000

# Other
export LISTMAX=0
export WORDCHARS="${WORDCHARS/\//}"

# Zsh options
setopt auto_cd
setopt auto_pushd
setopt pushd_minus
setopt pushd_ignore_dups

unsetopt list_beep
setopt list_packed
unsetopt list_types

setopt extended_history
unsetopt hist_beep
setopt hist_expand
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_no_store
setopt hist_reduce_blanks
setopt hist_save_no_dups
setopt hist_verify
setopt share_history

unsetopt bg_nice

unsetopt beep
